version: '3.4'
services:
  db:
    container_name: ep-mysql
    image: ep-mysql-img
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: __database__/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: "!12345"
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: EquipamentosEletricosDB
      LANG: C.UTF-8
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_0900_ai_ci
    ports:
        - 3306:3306
    networks:
      - ep-network

  server:
    container_name: ep-server
    image: ep-server-img    
    build:
      context: .
      dockerfile: __server__/Dockerfile    
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: development
    ports:
      - "3001:3001"      
    depends_on:
      - db
    networks:
      - ep-network

  client:
    container_name: ep-client
    image: ep-client-img
    build:
      context: .
      dockerfile: __client__/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - ep-network

networks:
    ep-network:
        driver: bridge