FROM node:lts-alpine as node
ENV NODE_ENV=development
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --silent && mv node_modules ../
COPY . ./
RUN npx prisma generate --schema schema.prisma
COPY ./.env.docker ./.env
EXPOSE 3001
RUN chown -R node /usr/src/app
USER node
CMD ["npm", "start"]
