version: '3.4'

services:
  equipamentos-eletricos-server:
    image: equipamentos-eletricos-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
