version: '3.4'

services:
  equipamentos-eletricos:
    container_name: client
    image: equipamentos-eletricos-client
    build:
      context: .
      dockerfile: ./Dockerfile-local
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000